server:
  port: 8888
  
  
  
eureka:
 client:
  serviceUrl:
    defaultZone: http://eureka-server:8761/eureka instance:  hostname: ${HOSTNAME}
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rogeriotakashi/Microservices-SAGA-Patterns-Configuration.git  application:    name: Configuration-Server

